config/routes.rb
Rails.application.routes.draw do

  resources :cargas
  resources :users
  get 'client/index', to: 'client#client_index'

  get 'admin/index', to: 'admin#admin_index'

  get 'signin/index'

  post 'login', to: 'signin#login'

  root 'home#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carga.rb
class Carga < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController


  before_action :require_admin

  def index

  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  helper_method :current_user

  def current_user
    puts session[:userToken]
    @current_user = User.find_by(token: session[:userToken]) if session[:userToken]
    return @current_user
  end


  def require_user
    redirect_to root_path unless current_user
  end

  def require_admin
    puts current_user.token
    puts current_user.level
    if current_user != nil and current_user.level != 4
      redirect_to root_path 
    end
  end





end

app/controllers/cargas_controller.rb
class CargasController < ApplicationController
  before_action :set_carga, only: [:show, :edit, :update, :destroy]

  # GET /cargas
  # GET /cargas.json
  def index
    @cargas = Carga.all
  end

  # GET /cargas/1
  # GET /cargas/1.json
  def show
  end

  # GET /cargas/new
  def new
    @carga = Carga.new
  end

  # GET /cargas/1/edit
  def edit
  end

  # POST /cargas
  # POST /cargas.json
  def create
    @carga = Carga.new(carga_params)

    respond_to do |format|
      if @carga.save
        format.html { redirect_to @carga, notice: 'Carga was successfully created.' }
        format.json { render :show, status: :created, location: @carga }
      else
        format.html { render :new }
        format.json { render json: @carga.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cargas/1
  # PATCH/PUT /cargas/1.json
  def update
    respond_to do |format|
      if @carga.update(carga_params)
        format.html { redirect_to @carga, notice: 'Carga was successfully updated.' }
        format.json { render :show, status: :ok, location: @carga }
      else
        format.html { render :edit }
        format.json { render json: @carga.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cargas/1
  # DELETE /cargas/1.json
  def destroy
    @carga.destroy
    respond_to do |format|
      format.html { redirect_to cargas_url, notice: 'Carga was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carga
      @carga = Carga.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carga_params
      params.require(:carga).permit(:user, :cajas, :costoManejo, :alto, :ancho, :largo, :pesoEstimado, :direccion, :valorAsegurado, :nombreDestinatario, :telefonoDestinatario, :recibeSabados, :flete, :fleteTotal, :guia)
    end
end

app/controllers/client_controller.rb
class ClientController < ApplicationController
  def client_index
  end
end

app/controllers/concerns/Tokenable.rb
module Tokenable
  extend ActiveSupport::Concern

  included do
    before_create :generate_token
  end

  protected

  def generate_token
    self.token = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless self.class.exists?(token: random_token)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/signin_controller.rb
class SigninController < ApplicationController


  def index
  end

  def login
    puts params
    puts params[:email]
    puts params[:password]

    @user = User.find_by(user: params[:email])
    puts @user
    if @user != nil
      if @user.password == params[:password]
        @user.token = generate_token
        if @user.save!
          puts "si guardo"
          puts @user.token
          session[:aja] = 1
          session[:userToken] = @user.token
          puts "--aca--"
          puts session[:userToken]
          puts "----"
          if @user.level == 1
            puts 1
            redirect_to client_index_path
          elsif @user.level == 4
            puts 2
            redirect_to admin_index_path
          else
            puts 3
          end
        end
      end

    end

  end

  def generate_token
    return SecureRandom.uuid
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user, :password, :level, :token, :nit, :address)
    end

    def generate_token
      self.token = loop do
        random_token = SecureRandom.urlsafe_base64(nil, false)
        break random_token unless ModelName.exists?(token: random_token)
      end
    end

    def token
      @token = "generate_token"
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cargas_helper.rb
module CargasHelper
end

app/helpers/client_helper.rb
module ClientHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/signin_helper.rb
module SigninHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_index.html.erb
<div id="page-wrapper" style="background-color: #FFFFFF;">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header" align="center" style="font-size: 3.5em; margin-top: 20px">Dashboard</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>

    <!-- /.row -->
    <div class="row">
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-comments fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">

                        </div>
                    </div>
                </div>
                <a href="#">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-yellow">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-shopping-cart fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div>New Orders!</div>
                        </div>
                    </div>
                </div>
                <a href="#">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
             <div class="panel panel-green">
                 <div class="panel-heading">
                     <div class="row">
                         <div class="col-xs-3">
                             <i class="fa fa-barcode fa-5x"></i>
                         </div>
                         <div class="col-xs-9 text-right">

                             <div>Stock available!</div>
                         </div>
                     </div>
                 </div>
                 <a href="#">
                     <div class="panel-footer">
                         <span class="pull-left">View Details</span>
                         <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                         <div class="clearfix"></div>
                     </div>
                 </a>
             </div>
         </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-red">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-ticket fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">0</div>
                            <div>Support Tickets!</div>
                        </div>
                    </div>
                </div>
                <a href="#">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-8">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bar-chart-o fa-fw"></i> Sales chart
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-usd fa-fw"></i> Latest sales
                    <div class="pull-right">
                        <div class="btn-group">
                        </div>
                    </div>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="table-responsive">
                                <table class="table table-bordered table-hover table-striped">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Created at</th>
                                            <th>Braintree ID</th>
                                            <th>Amount</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                    </tbody>
                                </table>
                            </div>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.col-lg-4 (nested) -->

                        <!-- /.col-lg-8 (nested) -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->

            <!-- /.panel -->
        </div>
        <!-- /.col-lg-8 -->
        <div class="col-lg-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bell fa-fw"></i> Notifications Panel
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="list-group">
                        <a href="#" class="list-group-item">
                            <i class="fa fa-comment fa-fw"></i> New Comment
                            <span class="pull-right text-muted small"><em>4 minutes ago</em>
                            </span>
                        </a>
                        <a href="#" class="list-group-item">
                            <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                            <span class="pull-right text-muted small"><em>12 minutes ago</em>
                            </span>
                        </a>
                        <a href="#" class="list-group-item">
                            <i class="fa fa-envelope fa-fw"></i> Message Sent
                            <span class="pull-right text-muted small"><em>27 minutes ago</em>
                            </span>
                        </a>
                        <a href="#" class="list-group-item">
                            <i class="fa fa-tasks fa-fw"></i> New Task
                            <span class="pull-right text-muted small"><em>43 minutes ago</em>
                            </span>
                        </a>
                        <a href="#" class="list-group-item">
                            <i class="fa fa-upload fa-fw"></i> Server Rebooted
                            <span class="pull-right text-muted small"><em>11:32 AM</em>
                            </span>
                        </a>
                        <a href="#" class="list-group-item">
                            <i class="fa fa-bolt fa-fw"></i> Server Crashed!
                            <span class="pull-right text-muted small"><em>11:13 AM</em>
                            </span>
                        </a>
                        <a href="#" class="list-group-item">
                            <i class="fa fa-warning fa-fw"></i> Server Not Responding
                            <span class="pull-right text-muted small"><em>10:57 AM</em>
                            </span>
                        </a>
                        <a href="#" class="list-group-item">
                            <i class="fa fa-shopping-cart fa-fw"></i> New Order Placed
                            <span class="pull-right text-muted small"><em>9:49 AM</em>
                            </span>
                        </a>
                        <a href="#" class="list-group-item">
                            <i class="fa fa-money fa-fw"></i> Payment Received
                            <span class="pull-right text-muted small"><em>Yesterday</em>
                            </span>
                        </a>
                    </div>
                    <!-- /.list-group -->
                    <a href="#" class="btn btn-default btn-block">View All Alerts</a>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->

            <!-- /.panel -->
            <!-- /.panel .chat-panel -->
        </div>
        <!-- /.col-lg-4 -->
    </div>
    <!-- /.row -->
</div>
<!-- /#page-wrapper -->

app/views/admin/_userlist.html.erb
 <div id="page-wrapper" style="background-color: #FFFFFF; margin-top: 15px">

<div class="container-fluid">

    <div class="pull-right">
      <a href="/admin/index" data-toggle="tooltip" title="Cancel" class="btn btn-default"><i class="fa fa-reply"></i></a></div>
      <h1>Users</h1>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i>Users</h3>
      </div>
      <div class="panel-body">
        <div class="tab-pane" id="tab-discount">
          <div class="table-responsive">
            <table id="discount" class="table table-striped table-bordered table-hover">
              <thead>
                <tr>
                  <td class="text-left">Id</td>
                  <td class="text-left">Email</td>
                  <td class="text-left">Role</td>
                  <td class="text-left">Status</td>
                  <td class="text-left">Action</td>
                </tr>
              </thead>
              <tbody>
                <% @userslist.each do |t| %>
                <tr>
                  <td><%= t.id %></td>
                  <td><%= t.email %></td>
                  <td><%= t.role %></td>

                  <td> Active </td>
                  <td><!-- <a href="/category/edit/<%= t.id %>" data-toggle="tooltip" title="Edit" class="btn btn-default"><i class="fa fa-pencil"></i></a>-->
                  <%= link_to '', beadmin_admin_index_path( :id => t.id ), :class=>"btn btn-default fa fa-arrow-circle-up", remote: true %>
                  <%= link_to '', removeadmin_admin_index_path( :id => t.id ), :class=>"btn btn-default fa fa-arrow-circle-down", remote: true %>
                  <!--<%= link_to '', status_category_index_path( :id => t.id ), :class=>"btn btn-default fa fa-eye", remote: true %>-->
                  <!-- <a href="/category/status/<%= t.id %>" data-toggle="tooltip" title="Active / Disable" class="btn btn-default"><i class="fa fa-eye"></i></a></td>
                  <a href="/admin/index" data-toggle="tooltip" title="Active / Disable" class="btn btn-default"><i class="fa fa-eye"></i></a></div></td> -->
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/admin/admin_index.html.erb
<div id="indexcambio">

  <%= render 'admin/index' %>

</div>

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/admin/userlist.js.erb
$( "#indexcambio" ).html( "<%= escape_javascript( render( "userlist" ) ) %>" );

app/views/cargas/_form.html.erb
<%= form_with(model: carga, local: true) do |form| %>
  <% if carga.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(carga.errors.count, "error") %> prohibited this carga from being saved:</h2>

      <ul>
      <% carga.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user %>
    <%= form.text_field :user, id: :carga_user %>
  </div>

  <div class="field">
    <%= form.label :cajas %>
    <%= form.number_field :cajas, id: :carga_cajas %>
  </div>

  <div class="field">
    <%= form.label :costoManejo %>
    <%= form.text_field :costoManejo, id: :carga_costoManejo %>
  </div>

  <div class="field">
    <%= form.label :alto %>
    <%= form.text_field :alto, id: :carga_alto %>
  </div>

  <div class="field">
    <%= form.label :ancho %>
    <%= form.text_field :ancho, id: :carga_ancho %>
  </div>

  <div class="field">
    <%= form.label :largo %>
    <%= form.text_field :largo, id: :carga_largo %>
  </div>

  <div class="field">
    <%= form.label :pesoEstimado %>
    <%= form.text_field :pesoEstimado, id: :carga_pesoEstimado %>
  </div>

  <div class="field">
    <%= form.label :direccion %>
    <%= form.text_field :direccion, id: :carga_direccion %>
  </div>

  <div class="field">
    <%= form.label :valorAsegurado %>
    <%= form.text_field :valorAsegurado, id: :carga_valorAsegurado %>
  </div>

  <div class="field">
    <%= form.label :nombreDestinatario %>
    <%= form.text_field :nombreDestinatario, id: :carga_nombreDestinatario %>
  </div>

  <div class="field">
    <%= form.label :telefonoDestinatario %>
    <%= form.text_field :telefonoDestinatario, id: :carga_telefonoDestinatario %>
  </div>

  <div class="field">
    <%= form.label :recibeSabados %>
    <%= form.number_field :recibeSabados, id: :carga_recibeSabados %>
  </div>

  <div class="field">
    <%= form.label :flete %>
    <%= form.text_field :flete, id: :carga_flete %>
  </div>

  <div class="field">
    <%= form.label :fleteTotal %>
    <%= form.text_field :fleteTotal, id: :carga_fleteTotal %>
  </div>

  <div class="field">
    <%= form.label :guia %>
    <%= form.text_field :guia, id: :carga_guia %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cargas/edit.html.erb
<h1>Editing Carga</h1>

<%= render 'form', carga: @carga %>

<%= link_to 'Show', @carga %> |
<%= link_to 'Back', cargas_path %>

app/views/cargas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cargas</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Cajas</th>
      <th>Costomanejo</th>
      <th>Alto</th>
      <th>Ancho</th>
      <th>Largo</th>
      <th>Pesoestimado</th>
      <th>Direccion</th>
      <th>Valorasegurado</th>
      <th>Nombredestinatario</th>
      <th>Telefonodestinatario</th>
      <th>Recibesabados</th>
      <th>Flete</th>
      <th>Fletetotal</th>
      <th>Guia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cargas.each do |carga| %>
      <tr>
        <td><%= carga.user %></td>
        <td><%= carga.cajas %></td>
        <td><%= carga.costoManejo %></td>
        <td><%= carga.alto %></td>
        <td><%= carga.ancho %></td>
        <td><%= carga.largo %></td>
        <td><%= carga.pesoEstimado %></td>
        <td><%= carga.direccion %></td>
        <td><%= carga.valorAsegurado %></td>
        <td><%= carga.nombreDestinatario %></td>
        <td><%= carga.telefonoDestinatario %></td>
        <td><%= carga.recibeSabados %></td>
        <td><%= carga.flete %></td>
        <td><%= carga.fleteTotal %></td>
        <td><%= carga.guia %></td>
        <td><%= link_to 'Show', carga %></td>
        <td><%= link_to 'Edit', edit_carga_path(carga) %></td>
        <td><%= link_to 'Destroy', carga, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Carga', new_carga_path %>

app/views/cargas/new.html.erb
<h1>New Carga</h1>

<%= render 'form', carga: @carga %>

<%= link_to 'Back', cargas_path %>

app/views/cargas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @carga.user %>
</p>

<p>
  <strong>Cajas:</strong>
  <%= @carga.cajas %>
</p>

<p>
  <strong>Costomanejo:</strong>
  <%= @carga.costoManejo %>
</p>

<p>
  <strong>Alto:</strong>
  <%= @carga.alto %>
</p>

<p>
  <strong>Ancho:</strong>
  <%= @carga.ancho %>
</p>

<p>
  <strong>Largo:</strong>
  <%= @carga.largo %>
</p>

<p>
  <strong>Pesoestimado:</strong>
  <%= @carga.pesoEstimado %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @carga.direccion %>
</p>

<p>
  <strong>Valorasegurado:</strong>
  <%= @carga.valorAsegurado %>
</p>

<p>
  <strong>Nombredestinatario:</strong>
  <%= @carga.nombreDestinatario %>
</p>

<p>
  <strong>Telefonodestinatario:</strong>
  <%= @carga.telefonoDestinatario %>
</p>

<p>
  <strong>Recibesabados:</strong>
  <%= @carga.recibeSabados %>
</p>

<p>
  <strong>Flete:</strong>
  <%= @carga.flete %>
</p>

<p>
  <strong>Fletetotal:</strong>
  <%= @carga.fleteTotal %>
</p>

<p>
  <strong>Guia:</strong>
  <%= @carga.guia %>
</p>

<%= link_to 'Edit', edit_carga_path(@carga) %> |
<%= link_to 'Back', cargas_path %>

app/views/client/client_index.html.erb
<div id="indexcambio">

  <%= render 'client/index' %>

</div>

app/views/layouts/_nav.html.erb
<div class="header" style="background-color: #666666">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <%= image_tag("home/logo.png", class: "img-responsive margin-auto") %>
            </div>
            <div class="col-lg-8">
                <div class="navigation">
                    <div id="navigation">
                        <ul>
                            <li class="active" style="font-size: 10px"><a href="index.html" title="Home">Inicio</a></li>
                            <li><a href="service-list.html" title="Service List">Quiénes somos</a></li>
                            <li><a href="blog-default.html" title="Blog ">Servicios</a>                           </li>
                            <li><a href="#" title="Features">Soluciones</a></li>
                            <li><a href="<%= signin_index_path %>" title="Features">Ingreso</a></li>
                            <li><a href="contact.html" title="Contact Us">Contacto</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Administrator</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'admin', media: 'all' %>
  </head>
  <body>
    <div id="wrapper">
    <%= render 'layouts/adminNav' %>
    <%= yield %>
    </div>
  </body>
</html>
<%= javascript_include_tag 'admin' %>

app/views/layouts/client.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Administrator</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'admin', media: 'all' %>
  </head>
  <body>
    <div id="wrapper">
    <%= render 'layouts/clientNav' %>
    <%= yield %>
    </div>
  </body>
</html>
<%= javascript_include_tag 'admin' %>

app/views/signin/hola.html.erb
<p><%= @token %></p>

app/views/signin/index.html.erb
<div class="container">
<div class="row" align="center">
    <h1>Ingreso</h1>
    <br><br>
    <div class="col-sm-12">
      <div class="col-sm-2" align="center"></div>
      <div class="col-sm-3 " align="center" style="outline: 1px solid red;">
        <br><br>

        <p>Por favor ingrese sus datos</p>

        <form accept-charset="UTF-8" method='post' action='<%= login_path	%>'>
          <div class="form-group" style="width: 100%">
            <label for="exampleInputEmail1">Email</label>
            <input type="email" name="email" class="form-control" value="" id="email" placeholder="Enter email">
            <small id="emailHelp" class="form-text text-muted">Nunca compartiremos su información personal</small>
          </div>
          <div class="form-group" style="width: 100%">
            <label for="exampleInputPassword1">Contraseña</label>
            <input type="password" name="password" class="form-control" value="" id="password" placeholder="Password">

          </div>

          <button class="button btn btn-success" type="submit"><span>Ingresar</span></button>
        </form>


        <br><br><br>
      </div>
      <div class="col-sm-6" align="center">
        <%= image_tag("home/logoNegro.png", class: "img-responsive margin-auto") %>

      </div>
      <div class="col-sm-12" align="center"><br><br><br></div>
    </div>
</div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Password</th>
      <th>Level</th>
      <th>Token</th>
      <th>Nit</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user %></td>
        <td><%= user.password %></td>
        <td><%= user.level %></td>
        <td><%= user.token %></td>
        <td><%= user.nit %></td>
        <td><%= user.address %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user.user %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Level:</strong>
  <%= @user.level %>
</p>

<p>
  <strong>Token:</strong>
  <%= @user.token %>
</p>

<p>
  <strong>Nit:</strong>
  <%= @user.nit %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/token.html.erb
<p><%= @token %></p>